name: Veracode SCA Test

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      frontend-repos: ${{ steps.set-frontend-repos.outputs.repos }}
      backend-repos: ${{ steps.set-backend-repos.outputs.repos }}
      other-repos: ${{ steps.set-other-repos.outputs.repos }}
    steps:
      - id: set-frontend-repos
        run: |
          echo "::set-output name=repos::$(jq -n '[ "repo1", "repo2" ]')"
      - id: set-backend-repos
        run: |
          echo "::set-output name=repos::$(jq -n '[ "repo3", "repo4" ]')"
      - id: set-other-repos
        run: |
          echo "::set-output name=repos::$(jq -n '[ "repo5", "repo6" ]')"

  generate-jobs:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Debug Outputs
        run: |
          echo "Frontend Repos: ${{ needs.setup.outputs.frontend-repos }}"
          echo "Backend Repos: ${{ needs.setup.outputs.backend-repos }}"
          echo "Other Repos: ${{ needs.setup.outputs.other-repos }}"

      - name: Create jobs script
        run: |
          echo '#!/bin/bash' > create_jobs.sh
          echo 'prev_job=""' >> create_jobs.sh
          for category in frontend-repos backend-repos other-repos; do
            repos="${{ needs.setup.outputs.${category} }}"
            for repo in $(echo "$repos" | jq -r '.[]'); do
              job_name="scan-$repo"
              echo "$job_name:" >> jobs.yml
              if [[ -n "$prev_job" ]]; then
                echo "  needs: $prev_job" >> jobs.yml
              fi
              echo "  runs-on: ubuntu-latest" >> jobs.yml
              echo "  steps:" >> jobs.yml
              echo "    - name: Echo repo" >> jobs.yml
              echo "      run: echo Repository: $repo" >> jobs.yml
              prev_job="$job_name"
            done
          done

      - name: Run job generation script
        run: |
          chmod +x create_jobs.sh
          ./create_jobs.sh
          cat jobs.yml >> $GITHUB_WORKSPACE/.github/workflows/veracode-test.yml

