name: Veracode SCA

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * 6"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to staging
        run: echo "Deploying to staging environment"

  run_tests:
    runs-on: ubuntu-latest
    needs: deploy_staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: echo "Running tests"

  deploy_production:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to production
        run: echo "Deploying to production environment"
